source 'https://rubygems.org'

# go to git masters until published gems catch up
gem 'robe', :path => '/users/col/dev/workspace/robe/gems/robe'
# gem 'robe', :git => 'https://github.com/balmoral/robe'
gem 'opal', :git => 'https://github.com/opal/opal' # 0.11.0.dev
gem 'opal-sprockets', :git => 'https://github.com/opal/opal-sprockets' # 0.11.0.dev
gem 'opal-browser', :git => 'https://github.com/opal/opal-browser'

# gem 'opal-highcharts', :git => 'https://github.com/balmoral/opal-highcharts'
gem 'opal-highcharts', :path => '/users/col/dev/workspace/opal/opal-highcharts'

gem 'thin' # or puma

